.travis.yml, defaults/main.yml, tasks/install.yml, vars/Debian.yml, vars/RedHat.yml
Prepare PostgreSQL YUM repository for setting up postgres related packages from `patroni_pkg_dependencies` list.
=> Add yum repo before installing packages on RedHat-like systems

handlers/main.yml, meta/main.yml, tasks/configure.yml, tasks/install.yml, tasks/watchdog.yml, tests/requirements.yml
- Install watchdog and `patroni_pkg_dependencies` via _package_ Ansible module;
- Reload systemd daemon using _systemd_ Ansible module (bump `galaxy_info.min_ansible_version` as dependent clause);
- Merge _reload systemd_ and _restart patroni_ handlers into a single one;
- Remove hardcoded consul role version and etcd role related variables.
=> Apply minor fixes

defaults/main.yml, templates/patroni.service.j2
Make log level configurable from environment variables (PATRONI_LOGLEVEL, PATRONI_REQUESTS_LOGLEVEL).
=> Add new features from patroni 1.4.3

defaults/main.yml, meta/main.yml
Hi,
can you add this? and would be good if you use also use github release for better versioning.
nice role anyway :)
Jacopo
=> don't use meta dependencies if they already exist

handlers/main.yml, tasks/configure.yml, tasks/install.yml, tasks/main.yml, tasks/watchdog.yml, templates/patroni-watchdog.service.j2
=> Make watchdog available for Patroni after OS reboot

TODO.md, defaults/main.yml, templates/patroni.yml.j2
Will be merged into the master branch, once `keep_existing_recovery_conf` feature of custom bootstrap methods in patroni project will be officially released.
Fixes #19
=> Add support of custom bootstrap methods

defaults/main.yml, tasks/install.yml
=> Don't use hardcoded pip packages for patroni

defaults/main.yml, templates/dcs/consul.yml.j2
Add config parameters related to registering of patroni service in consul.
=> Register service in consul

defaults/main.yml, templates/patroni.yml.j2
Read https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#building-replicas to get more details.
=> Support of multiple replica creation methods

defaults/main.yml, templates/patroni.yml.j2
=> Support of remove_data_directory_on_diverged_timelines

defaults/main.yml, templates/patroni.yml.j2
=> Support of bootstrap.dcs.check_timeline

defaults/main.yml, vars/Debian.yml, vars/RedHat.yml
=> Extend the list of default system packages

defaults/main.yml, templates/patroni.yml.j2
=> Standby cluster support

defaults/main.yml, templates/dcs/consul.yml.j2
=> Set default consul consistency mode

defaults/main.yml, meta/main.yml, tasks/configure.yml
Applied multiple minor changes to make yamllint and ansible-lint happy during Ansible Galaxy's "LINTING ROLE" stage.
=> Minor fixes to make linters happy

defaults/main.yml, templates/dcs/etcd.yml.j2
=> Support of etcd.use_proxies

README.md, defaults/main.yml, meta/main.yml
=> Do not enforce dependencies

defaults/main.yml, tasks/configure.yml, templates/patroni.service.j2, templates/patroni.yml.j2
Starting from Patroni 1.5.4 logging could be configured from config file.
=> Flexible logging support

tasks/watchdog.yml, templates/patroni-watchdog.service.j2
As discussed in https://github.com/kostiantyn-nemchenko/ansible-role-patroni/issues/69
=> Switch watchdog device permissions to udev rule

defaults/main.yml, vars/RedHat.yml
=> Optimize YUM variables

defaults/main.yml, tasks/configure.yml
This request closes #80. Changes are backward compatible.
=> Add ability to change scripts path

defaults/main.yml, templates/patroni.yml.j2
Add RestAPI options below:
* keyfile_password
* cafile
* ciphers
* verify_client
* http_extra_headers
* https_extra_headers
https://patroni.readthedocs.io/en/latest/SETTINGS.html#rest-api
=> Add several options for RestAPI
